// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  post_content: dynamic(() => import("./PostContent")),
  rich_text: dynamic(() => import("./RichText")),
};
